DROP TABLE OA_ACCOUNT;
CREATE TABLE OA_ACCOUNT(
  OA_ID INT NOT NULL IDENTITY (1,1),
  OA_ACCOUNT VARCHAR(40),
  OA_PWD VARCHAR(40),
  CREATE_DATE DATETIME
);
ALTER TABLE OA_ACCOUNT ADD CONSTRAINT PK1_OA_ID PRIMARY KEY(OA_ID);

DROP TABLE S_USER;
CREATE TABLE S_USER(
  USER_ID INT NOT NULL IDENTITY (1,1),
  USERNAME VARCHAR(40),
  MOBILE CHAR(11),
  DEPT_id INT,
  ROLE_ID INT,
  OA_ID INT ,
  CREATE_DATE DATETIME
);
ALTER TABLE S_USER ADD CONSTRAINT PK2_USER_ID PRIMARY KEY(USER_ID);

DROP TABLE S_ROLE;
CREATE TABLE S_ROLE(
  ROLE_ID INT NOT NULL IDENTITY (1,1),
  ROLE_NAME VARCHAR(40),
  ROLE_LEVEL INT,
  CREATE_DATE DATETIME
);
ALTER TABLE S_ROLE ADD CONSTRAINT PK3_ROLE_ID PRIMARY KEY(ROLE_ID);


DROP TABLE S_DEPT;
CREATE TABLE S_DEPT(
  DEPT_ID INT NOT NULL IDENTITY (1,1),
  DEPT_NAME VARCHAR(40),
  CREATE_DATE DATETIME
);
ALTER TABLE S_DEPT ADD CONSTRAINT PK4_DEPT_ID PRIMARY KEY(DEPT_ID);
